### ISSUE TITLE
Correct the mean quality score

### ISSUE THREAD

**Issue by mebbert** [conchoecia/pauvre#16]
Quality scores are currently inflated because we're taking the mean across the scores. The scores are in log scale, so, if we want to take the arithmetic mean of the non-log quality scores, we need to  we need take the log of the mean we're currently calculating. This is how albacore calculates the average score.

The question is whether the arithmetic mean or some other value is more appropriate. The arithmetic mean is only meaningful if the distribution of individual base quality scores is normally distributed. Otherwise, a geometric mean, or the median would be more approapriate. Incidentally, the mean of the log scores (like we're currently calculating) is the geometric mean.

**Comment by conchoecia** [comment]
You're totally right, I didn't think about that. Have you looked at the distributions of individual quality scores though? Do we know that they are not log-normal?

> so, if we want to take the arithmetic mean of the non-log quality scores, we need to we need take the log of the mean we're currently calculating. This is how albacore calculates the average score.

You're saying we should report this value, if I understand correctly?

![codecogseqn](https://user-images.githubusercontent.com/3123273/27495639-bd5a7a0c-5820-11e7-823e-fcd0394ad188.gif)

Math *really* isn't my strong suite, but the above seems different from this, which is what I think we should ideally report and what you're saying above.

![codecogseqn 1](https://user-images.githubusercontent.com/3123273/27495713-1a068a98-5821-11e7-8794-a62dc09f42a4.gif)
