### ISSUE TITLE
matplotlib.use() must be called *before* pylab

### ISSUE THREAD

**Issue by ghost** [conchoecia/pauvre#18]
Got the following error messages when running pauvre:
``pauvre_env/lib/python3.5/site-packages/matplotlib/__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.``

But the command worked nevertheless.

**Comment by conchoecia** [comment]
Thanks! I'll check this out...

**Comment by conchoecia** [comment]
I've looked into this and I'm going to leave the warning there for the time being. I found some info here: https://stackoverflow.com/questions/16170989 . Leaving the warning because if I suppress it, other users may miss errors that cause no-output in future versions.

**Comment by wdecoster** [comment]
I indeed think hiding warnings is not what you want, but the warning would be resolved if you use it like this:

```python
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
```
(at least, that's how I have it for NanoPlot...)

I added these lines after a suggestion in this issue: https://github.com/wdecoster/NanoPlot/issues/1#issuecomment-307097660
see also https://stackoverflow.com/questions/37604289/tkinter-tclerror-no-display-name-and-no-display-environment-variable

But this is a violation of pep8 :-) however, it's also specified as this in the matplotlib faq: https://matplotlib.org/faq/howto_faq.html#generate-images-without-having-a-window-appear

**Comment by conchoecia** [comment]
Thanks for pointing that out, @wdecoster , I encounted some more errors on my server today regarding this issue. I wouldn't worry about pep8 since it is such a small thing that will make the software work as you intend. 

Reference to the error I am encountering here: `https://stackoverflow.com/questions/37604289`

**Comment by abayega** [comment]
Problem solved, thanks

**Comment by zqs01** [comment]
In this circumstance, you need to upgrade matplotlib, then the warning will disappear.
use `pip install --upgrade matplotlib`
