### ISSUE TITLE
plot not showing

### ISSUE THREAD

**Issue by Dramenia** [conchoecia/pauvre#19]
when using the command pauvre marginplot --fastq file.fastq, i get the results from the stats, but the plot is not showing up.

I run the command locally on a ubuntu machine with python3 and all dependencies installed.
I dont receive any errors. any clue what i am missing?

**Comment by conchoecia** [comment]
When you say showing up, do you mean appear on your screen? The program saves the plot as a file in the directory in which you run it, and you can select one or multiple file formats by using `--fileform pdf png etc`.

**Comment by Dramenia** [comment]
Thanks for the hint.
The problem was indeed with the saving of the plot. i didnt got an error, but it seems that the program didnt have any writing options on that directory. after sudo, i did receive the plots.
Thank you! i will close the issue
________________________________

**Comment by Dramenia** [comment]
Issue resolved by sudoing pauvre. the program could not write to the directory due to writing permissions.

**Comment by conchoecia** [comment]
Glad to hear it works for you now!

**Comment by wdecoster** [comment]
Probably wouldn't be too hard to have pauvre check for write permission? I'm a bit surprised no error is produced. NanoPlot checks for write permission when creating the log file (https://github.com/wdecoster/NanoPlot/blob/master/nanoplot/NanoPlot.py#L122)

**Comment by conchoecia** [comment]
Thanks for the suggestion, @wdecoster. I just tried out my script in a directory where I didn't have write permissions on mac and got the following error:

```
  File "/Users/darrin/anaconda/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 550, in print_png
    filename_or_obj = open(filename_or_obj, 'wb')
PermissionError: [Errno 13] Permission denied: 'miniDSMN15.png'
```

So, it's a PermissionError I guess. I'll write a try:except block to catch that error type, instead of a more general exception type.
