### ISSUE TITLE
_tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by abayega** [conchoecia/pauvre#20]
Hi,

do you know where this error is coming from?

File "......./CentOS6/python64/3.5.2/lib/python3.5/tkinter/__init__.py", line 1868, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by conchoecia** [comment]
Thanks! I'll look into this - I don't have a CentOS system though so I'll see what I can dig up...

**Comment by wdecoster** [comment]
That tcl error is suggestive of something related to X11 tunnelling I think. Was `ssh -X` used for logging in?

**Comment by abayega** [comment]
I installed pauvre on our cluster so I use ssh <my login credentials> to log on but not ssh -X.

Thanks

**Comment by wdecoster** [comment]
I think this can be solved by making this change: https://github.com/conchoecia/pauvre/issues/18#issuecomment-320992711

**Comment by conchoecia** [comment]
Thanks, @wdecoster!
