### ISSUE TITLE
Turn off transparent background in plotting - problem

### ISSUE THREAD

**Issue by Tman3** [conchoecia/pauvre#33]
Attempt to turn off the transparent background to make a white background.  However, I got the error message.  If I don't us the --transparent option, the command works.
Command line:
`pauvre marginplot --transparent False --fastq myfile.fq`

Error message:
```
usage: pauvre [-h] [-v] {marginplot,redwood,stats,synplot} ...
pauvre: error: unrecognized arguments: --transparent False myfile.fq
```

**Comment by wdecoster** [comment]
Can you try that command with `--no-transparent` without adding 'False'?

**Comment by conchoecia** [comment]
Hi @Tman3,

If you type `pauvre marginplot` or `pauvre marginplot --help` you will see the command line arguments.

You will see that the argument to turn transparency off is:

```
  -n, --no-transparent  Not the TV show. Specify this option if you don't want
                        a transparent background. Default is on.
``` 

So, just add the `-n` or `--no-transparent` flag and you will get a plot.

Thanks and feel free to follow up.

**Comment by Tman3** [comment]
Hi Darrin:
Thanks! the -n parameter work.
