### ISSUE TITLE
make gffutils install when installing through pip

### ISSUE THREAD

**Issue by conchoecia** [conchoecia/pauvre#34]

**Comment by merwok** [comment]
Is this issue about adding gffutils to the dependencies?

**Comment by conchoecia** [comment]
Yes - although gffutils isn't used for anything relevant to marginplot. Closing for now as this isn't pressing.

**Comment by merwok** [comment]
I see it imported in pauvre.browser, so that module wouldn’t work.
Are people supposed to not use it?
