### ISSUE TITLE
Please use version tags

### ISSUE THREAD

**Issue by tillea** [conchoecia/pauvre#38]
Hi,
I intend to package pauvre for Debian since [NanoPlot](https://github.com/wdecoster/NanoPlot) depends on it and NanoPlot is a target in our Debian Med COVID-19 sprint.  The versioned dependency in NanoPlot is pauvre>=0.1.86.  I can find some [v0.1.86 snapshot](https://github.com/conchoecia/pauvre/releases/tag/0.1.86) tag here.  But no later tags.  When looking at [pipy](https://pypi.org/project/pauvre/#files) the version scheme is different and recently released versions seem to lack the '.' to separate minor and micro versions.  It would be very helpful if you would use a clear versioning scheme and if you would tag your github releases in sync with the pipy versions.
Thanks a lot, Andreas.

**Comment by conchoecia** [comment]
Is there something specific that I can do at the moment to help with your effort?

**Comment by tillea** [comment]
On Mon, Apr 27, 2020 at 01:07:57PM -0700, darrin t schultz wrote:
> Is there something specific that I can do at the moment to help with your effort?

     git tag latest_version
     git push --tags

should be sufficient.  Hope this helps, Andreas.

**Comment by conchoecia** [comment]
Thanks @tillea - took the plunge and I think I get tags now. Tag a version when you want to release it, after committing. Current version tagged at v0.2 and uploaded to pypi.

**Comment by tillea** [comment]
On Fri, May 01, 2020 at 09:47:28PM -0700, darrin t schultz wrote:
> Thanks @tillea - took the plunge and I think I get tags now. Tag a version when you want to release it, after committing. Current version tagged at v0.2 and uploaded to pypi.
Thanks a lot.  That's very helpful.
Just a question:  The tagged release download from github includes the dir pauvre/bioawk and files which are not inside the pypi release.  What is the role of these two directories?
Kind regards, Andreas.

**Comment by conchoecia** [comment]
They're for development.
