### ISSUE TITLE
Matplotlib text.latex.unicode rcparam deprecation warning

### ISSUE THREAD

**Issue by emollier** [conchoecia/pauvre#41]
Greetings,

While running the test suite, the following warning appears repeatedly:
```
/usr/lib/python3.8/_collections_abc.py:832: MatplotlibDeprecationWarning:
The text.latex.unicode rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
  self[key] = other[key]
```
Reading through [Matplotlib API chages for version 3.0](https://matplotlib.org/devdocs/api/prev_api_changes/api_changes_3.0.0.html#changes-regarding-the-text-latex-unicode-rcparam), it would seem that the parameter will be forced to _True_ in the future.  However, in _pauvre/rcparams.py_, it is currently set to _False_, so I'm not sure how you would wish to move forward on this topic.  Anyway, for information...

Kind Regards

**Comment by conchoecia** [comment]
Thank you. I'll try to update to remove the deprecation warning.
