### ISSUE TITLE
Matplotlib

### ISSUE THREAD

**Issue by alexiswl** [conchoecia/pauvre#5]
#Hello,

Thank you for your package, I've been able to produce some awesome plots like those that I used to get with Metrichor (back when it was free).

When using Unix I could only get this to work by adding
'matplotlib.use("Agg")' after import matplotlib in the marginplot.py script.

I understand that this may cause issues for those not using unix but would you mind adding it in as a comment and inform people that they just need to remove the '#' when they get this error:
"raise RuntimeError('Invalid DISPLAY variable')" 

Also, as someone who often fails to read the rest of the read me as soon as they see 'pip...'
would you mind changing 'pip' to 'pip3' in the README.md. My pip automatically reverts to my anaconda2 distribution instead and the #!/usr/bin/env python could also be #!/usr/bin/env python3 to prevent one having to type python3 before any command.

Thanks again, I'll be sure to continue using this package.

Kind Regards,
Alexis.

**Comment by conchoecia** [comment]
Thanks for your comments. I'll get to this issue this weekend. Glad you like it so far, despite the bugs!
