### ISSUE TITLE
Unable to find pixel distance along axis

### ISSUE THREAD

**Issue by Thuurslangen** [conchoecia/pauvre#6]
I am following your protocol and got the next message:

![image](https://cloud.githubusercontent.com/assets/20397906/26728752/95ebc2c6-47ab-11e7-9b8b-70b45806a240.png)

**Comment by conchoecia** [comment]
Thanks for posting. Would you mind responding with the command that you used to generate this error?

**Comment by Thuurslangen** [comment]
pauvre marginplot --maxlen 4000 --maxqual 25 --lengthbin 50 --fileform pdf png --qualbin 0.5 --fastq C:\Users\Nanopore\Downloads\reads\fastq_runid_c578f82c5d542d807b5c07f058b2c6a665e252d9_0.fastq

**Comment by Thuurslangen** [comment]
and also with the normal command line:
![image](https://user-images.githubusercontent.com/20397906/26875976-72f783ae-4b84-11e7-94bc-a19c1823540d.png)

**Comment by conchoecia** [comment]
Hi @Thuurslangen, I haven't been able to replicate this problem on Mac or Ubuntu. Do you encounter this error with every `.fastq` file you try in the Windows environment, or is it specifically just this file? If it is just this file, then perhaps you could share it with me. Otherwise, I will need to find a windows machine to test the sotfware on.

**Comment by scogi** [comment]
Hi! I managed only today to test pauvre, too. 
I am getting the same error as Thuurslangen on Ubuntu 16.04 with two different fastq I tested.
Python is 2.7. I did not manage to install on 3.4 (gives several errors) 

![image](https://user-images.githubusercontent.com/24541473/27281561-9d61b440-54ec-11e7-8a36-1d5f19025a89.png)

**Comment by scogi** [comment]
Hi!

Was finally able to solve this. After updating numpy to the latest version, pauvre could be installed also in python 3.4. There the issue described did not appear. Running pauvre in python 2.7 seems to have been the cause

**Comment by conchoecia** [comment]
@Coassin thanks for looking into this. Do you have any idea of the previous version of `numpy` that you were using? If you have a ballpark estimate I can make sure that `pip` installs the latest version when installing `pauvre` in the future.

**Comment by scogi** [comment]
Sorry, I did not track this. Do you know whether I can find this somewhere in any log files?

**Comment by conchoecia** [comment]
@Coassin, I'm not sure, but thanks for offering to check! I'll just use my current installed versions to verify that it is working.
