### ISSUE TITLE
Add Biopython as a pre-requisite

### ISSUE THREAD

**Issue by mebbert** [conchoecia/pauvre#7]
Hi,

Thanks for the nice package. I hadn't installed Biopython, which is a pre-requisite for your code. Would be good to add that to your README.

Best,

Mark

**Comment by conchoecia** [comment]
Thanks for the suggestion, @mebbert. When using `pip3 install pauvre`, `pip` should now automatically install the dependencies.

**Comment by wdecoster** [comment]
Hi,

I believe it should be 'biopython' and not 'Bio' in your setup.py

Cheers,  
Wouter

**Comment by conchoecia** [comment]
Thanks! I fixed that in the current release. I always mix the import and install statements up...

**Comment by wdecoster** [comment]
The only reason I know it shouldn't be 'Bio' is because I initially also messed up ;-)
